name: 'Auto Release Draft'
description: 'Drafts a GitHub release with the changes introduced by a newly created version tag.'
author: 'Gregor Suttie aka Azure Greg'
outputs:
  release-url:
    description: 'The url of the GitHub release that was drafted'
runs:
  using: 'node12'
  main: 'dist/index.js'
