name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
      fail-fast: true
    steps:
      - name: Get the source code
        uses: actions/checkout@v1
      - name: Restore the dependencies
        run: npm ci
      - name: Build
        run: npm run all  
